name: Build and Deploy to Production

on:
  push:
    branches: [ main ]
    # Only run if commit message contains [build]
  workflow_dispatch:

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build]')
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest
    - name: Debug - Check files
      run: |
        echo "Current directory:"
        pwd
        echo "Files in current directory:"
        ls -la
        echo "Files in directory:"
        ls -la
        echo "Looking for package.json:"
        find . -name "package.json" -type f
        echo "Looking for bun.lock:"
        find . -name "bun.lock" -type f
    - name: Install dependencies
      run: |
        bun install
    - name: Run type checking and build
      run: |
        bun run build
    - name: List build artifacts
      run: |
        echo "Build completed successfully!"
        ls -la dist/
        echo "Total files in dist/:"
        find dist/ -type f | wc -l
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/
        retention-days: 7

  deploy:
    name: Deploy to Web Server
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && (github.event_name == 'workflow_dispatch' || contains(github.event.head_commit.message, '[build]'))
    
    steps:
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist/
        
    - name: Verify downloaded files
      run: |
        echo "Files ready for deployment:"
        ls -la dist/
        
    - name: Deploy via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        # Use FTP or another file sharing service to upload the website files automatically when a build occurs
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /public_html/site/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env*
          **/.DS_Store
        
    - name: Clean orphaned files  
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /public_html/site/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env*
          **/.DS_Store
          **/.htaccess
